version: '3.5'

services:
  php8-app:
    build:
      context: '.'
    container_name: php8-app
    volumes:
      - ../app:/var/www/html
    ports:
      - 8000:80
    entrypoint:
      - /root/init.sh
