## PHP 8.0 on Docker

This is example of docker-compose build to run **php8.0** on Docker.
It includes Apache and most needed php extentions.

### Installation
Clone this repository and run

```sh
$ docker-compose up -d
```

After that go to the ``localhost:8000``
